src/Entity/Invoice.php
<?php

namespace App\Entity;

use App\Repository\InvoiceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: InvoiceRepository::class)]
class Invoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'date')]
    private $invoice_date;

    #[ORM\Column(type: 'integer')]
    private $invoice_number;

    #[ORM\Column(type: 'integer')]
    private $customer_id;

    #[ORM\OneToMany(mappedBy: 'invoice_id', targetEntity: InvoiceLines::class)]
    private $invoiceLines;

    public function __construct()
    {
        $this->invoiceLines = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoiceDate(): ?\DateTimeInterface
    {
        return $this->invoice_date;
    }

    public function setInvoiceDate(\DateTimeInterface $invoice_date): self
    {
        $this->invoice_date = $invoice_date;

        return $this;
    }

    public function getInvoiceNumber(): ?int
    {
        return $this->invoice_number;
    }

    public function setInvoiceNumber(int $invoice_number): self
    {
        $this->invoice_number = $invoice_number;

        return $this;
    }

    public function getCustomerId(): ?int
    {
        return $this->customer_id;
    }

    public function setCustomerId(int $customer_id): self
    {
        $this->customer_id = $customer_id;

        return $this;
    }

    /**
     * @return Collection<int, InvoiceLines>
     */
    public function getInvoiceLines(): Collection
    {
        return $this->invoiceLines;
    }

    public function addInvoiceLine(InvoiceLines $invoiceLine): self
    {
        if (!$this->invoiceLines->contains($invoiceLine)) {
            $this->invoiceLines[] = $invoiceLine;
            $invoiceLine->setInvoiceId($this);
        }

        return $this;
    }

    public function removeInvoiceLine(InvoiceLines $invoiceLine): self
    {
        if ($this->invoiceLines->removeElement($invoiceLine)) {
            // set the owning side to null (unless already changed)
            if ($invoiceLine->getInvoiceId() === $this) {
                $invoiceLine->setInvoiceId(null);
            }
        }

        return $this;
    }
}

src/Controller/InvoiceController.php
<?php

namespace App\Controller;

use App\Entity\Invoice;
use App\Entity\InvoiceLines;
use App\Form\InvoiceFormType;
use App\Form\InvoicelinesFormType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class InvoiceController extends AbstractController
{
    #[Route('/', name: 'app_invoice')]
    public function index(Request $request, ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $tva = 18;
        $invoice = new Invoice();
        $invoiceLine = new Invoicelines();
        $invoice->getInvoicelines()->add($invoiceLine);
        $form = $this->createForm(InvoiceFormType::class, $invoice);

        if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
            $lines = $invoice->getInvoicelines();
            $last_id_record =  $em->getRepository(Invoice::class)->findOneBy([], ['id' => 'desc']);
            $invoice->setInvoiceNumber($last_id_record ?  (int)$last_id_record->getId() + 1 : 1);
            $em->persist($invoice);
            foreach($lines as $singleLine ){
                $amount_without_vat = $singleLine->getQuantity() * $singleLine->getAmount();
                $amount_vat = ($amount_without_vat * $tva) / 100;
                $total = $amount_vat + $amount_without_vat;
                $singleLine->setTotalWithVat($total);
                $singleLine->setVatAmount($amount_vat);
                $singleLine->setInvoice($invoice);
                $em->persist($singleLine);
            }

            $em->flush();
            unset($form);
            unset($invoice);
            unset($line);
            $invoice = new Invoice();
            $line = new Invoicelines();
            $invoice->getInvoiceLines()->add($line);
            $form = $this->createForm(InvoiceFormType::class, $invoice);
        }

        return $this->render('invoice/index.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/invoice/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}INVOICE PAGE{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>New Invoice</h1>
        {{ form_start(form) }}
        {{ form_row(form.invoiceDate) }}
        {{ form_row(form.customerId) }}
        <h3>Lines</h3>
        <div class="row invocelines"
             data-index="{{ form.invoicelines|length > 0 ? form.invoicelines|last.vars.name : 0 }}"
             data-prototype="{{ form_widget(form.invoicelines.vars.prototype)|e('html_attr') }}">
            {% for line in form.invoicelines %}
                <div class="col-4">{{ form_row(line.description) }}</div>
                <div class="col-4">{{ form_row(line.quantity) }}</div>
                <div class="col-4">{{ form_row(line.amount) }}</div>
            {% endfor %}
        </div>
        <button type="button" class="add_item_link btn btn-secondary" data-collection-holder-class="invocelines">Add a
            line
        </button>
        {{ form_end(form) }}
    </div>

    <script type="text/javascript">
        const addFormToCollection = (e) => {
            const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);
            console.log(collectionHolder.dataset.index);
            const item = document.createElement("div");
            item.innerHTML = collectionHolder
                .dataset
                .prototype
                .replace(
                    /__name__/,
                    collectionHolder.dataset.index
                );
            collectionHolder.appendChild(item);
            el = document.getElementById('invoce_form_invocelines_' + collectionHolder.dataset.index);
            el.classList.add('row');
            for (var i = 0; i < el.children.length; i++) {
                var child = el.children[i];
                if (child.tagName == 'DIV') {
                    child.classList.add('col-4');
                }
            }
            collectionHolder.dataset.index++;
        };
        document.querySelectorAll('.add_item_link').forEach(btn => {
            btn.addEventListener("click", addFormToCollection);
        });
    </script>
{% endblock %}